// Auto-generated from src/routes/posr.ts — 312 reports in 13 categories
// Do not edit manually. Regenerate with: python3 scripts/gen-feature-hub-data.py

export interface FeatureHubReport {
  name: string;  // REPORTS_ constant name
  path: string;  // route path (without /reports/ prefix)
  title: string; // human-readable title
  category: string;
  icon: string;  // icon key
}

export const FEATURE_HUB_REPORTS: FeatureHubReport[] = [
  { name: "BUFFET", path: "buffet", title: "Buffet", category: "AI Forecasting", icon: "chartLine" },
  { name: "BUFFET_DEMAND", path: "buffet-demand", title: "Buffet Demand", category: "AI Forecasting", icon: "chartLine" },
  { name: "CHURN_PREDICTION", path: "churn-prediction", title: "Churn Prediction", category: "AI Forecasting", icon: "chartLine" },
  { name: "CLV_TRAJECTORY", path: "clv-trajectory", title: "Clv Trajectory", category: "AI Forecasting", icon: "chartLine" },
  { name: "CUSTOMER_CLV", path: "customer-clv", title: "Customer Clv", category: "AI Forecasting", icon: "chartLine" },
  { name: "CUSTOMER_LTV_MULTIPLIER", path: "customer-ltv-multiplier", title: "Customer Ltv Multiplier", category: "AI Forecasting", icon: "chartLine" },
  { name: "EXPIRY_TRACKER", path: "expiry-tracker", title: "Expiry Tracker", category: "AI Forecasting", icon: "chartLine" },
  { name: "FORECAST", path: "forecast", title: "Forecast", category: "AI Forecasting", icon: "chartLine" },
  { name: "FORECAST_ACCURACY", path: "forecast-accuracy", title: "Forecast Accuracy", category: "AI Forecasting", icon: "chartLine" },
  { name: "HIRING_PREDICTOR", path: "hiring-predictor", title: "Hiring Predictor", category: "AI Forecasting", icon: "chartLine" },
  { name: "KITCHEN_DEMAND_SURGE", path: "kitchen-demand-surge", title: "Kitchen Demand Surge", category: "AI Forecasting", icon: "chartLine" },
  { name: "LABOR_FORECAST", path: "labor-forecast", title: "Labor Forecast", category: "AI Forecasting", icon: "chartLine" },
  { name: "NOSHOW_PREDICTION", path: "no-show-prediction", title: "Noshow Prediction", category: "AI Forecasting", icon: "chartLine" },
  { name: "OCCASION_PREDICTION", path: "occasion-prediction", title: "Occasion Prediction", category: "AI Forecasting", icon: "chartLine" },
  { name: "OVERTIME_PREDICTION", path: "overtime-prediction", title: "Overtime Prediction", category: "AI Forecasting", icon: "chartLine" },
  { name: "PLATE_WASTE_PREDICTOR", path: "plate-waste-predictor", title: "Plate Waste Predictor", category: "AI Forecasting", icon: "chartLine" },
  { name: "PREDICTIVE_ORDERING", path: "predictive-ordering", title: "Predictive Ordering", category: "AI Forecasting", icon: "chartLine" },
  { name: "PROCUREMENT", path: "procurement", title: "Procurement", category: "AI Forecasting", icon: "chartLine" },
  { name: "PROMO_FORECAST", path: "promo-forecast", title: "Promo Forecast", category: "AI Forecasting", icon: "chartLine" },
  { name: "RECIPE_COST_VOLATILITY", path: "recipe-cost-volatility", title: "Recipe Cost Volatility", category: "AI Forecasting", icon: "chartLine" },
  { name: "REORDER_POINT_OPTIMIZER", path: "reorder-point-optimizer", title: "Reorder Point Optimizer", category: "AI Forecasting", icon: "chartLine" },
  { name: "REVENUE_FORECAST", path: "revenue-forecast", title: "Revenue Forecast", category: "AI Forecasting", icon: "chartLine" },
  { name: "SATISFACTION_PREDICTION", path: "satisfaction-prediction", title: "Satisfaction Prediction", category: "AI Forecasting", icon: "chartLine" },
  { name: "SEASONAL_DEMAND_SHIFT", path: "seasonal-demand-shift", title: "Seasonal Demand Shift", category: "AI Forecasting", icon: "chartLine" },
  { name: "SHRINKAGE", path: "shrinkage-detection", title: "Shrinkage", category: "AI Forecasting", icon: "chartLine" },
  { name: "SPOILAGE_PREDICTION", path: "spoilage-prediction", title: "Spoilage Prediction", category: "AI Forecasting", icon: "chartLine" },
  { name: "STAFF_PERFORMANCE_PREDICTION", path: "staff-performance-prediction", title: "Staff Performance Prediction", category: "AI Forecasting", icon: "chartLine" },
  { name: "TABLE_TURNOVER_PREDICTOR", path: "table-turnover-predictor", title: "Table Turnover Predictor", category: "AI Forecasting", icon: "chartLine" },
  { name: "WAIT_PREDICTION", path: "wait-prediction", title: "Wait Prediction", category: "AI Forecasting", icon: "chartLine" },
  { name: "YIELD_VARIANCE", path: "yield-variance", title: "Yield Variance", category: "AI Forecasting", icon: "chartLine" },
  { name: "ALCOHOL_COMPLIANCE_MONITOR", path: "alcohol-compliance-monitor", title: "Alcohol Compliance Monitor", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "ALLERGEN_RISK", path: "allergen-risk", title: "Allergen Risk", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "ANOMALY_ALERTS", path: "anomaly-alerts", title: "Anomaly Alerts", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "COMPLIANCE_TRACKING", path: "compliance-tracking", title: "Compliance Tracking", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "FOOD_SAFETY", path: "food-safety", title: "Food Safety", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "ONLINE_FRAUD_DETECTOR", path: "online-fraud-detector", title: "Online Fraud Detector", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "ORDER_FISCAL", path: "order-fiscal", title: "Order Fiscal", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "ORDER_FRAUD", path: "order-fraud", title: "Order Fraud", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "ORDER_PATTERN_ANOMALY", path: "order-pattern-anomaly", title: "Order Pattern Anomaly", category: "Compliance & Safety", icon: "shieldHalved" },
  { name: "BLOCKCHAIN_LOYALTY_TOKENIZED_REWARDS", path: "blockchain-loyalty-tokenized-rewards", title: "Blockchain Loyalty Tokenized Rewards", category: "Customer Experience", icon: "heart" },
  { name: "CUSTOMER_JOURNEY", path: "customer-journey", title: "Customer Journey", category: "Customer Experience", icon: "heart" },
  { name: "FEEDBACK_LOOP", path: "feedback-loop", title: "Feedback Loop", category: "Customer Experience", icon: "heart" },
  { name: "FIRST_VISIT_CONVERSION", path: "first-visit-conversion", title: "First Visit Conversion", category: "Customer Experience", icon: "heart" },
  { name: "GUEST_PREFERENCES", path: "guest-preferences", title: "Guest Preferences", category: "Customer Experience", icon: "heart" },
  { name: "JOURNEY_FRICTION", path: "journey-friction", title: "Journey Friction", category: "Customer Experience", icon: "heart" },
  { name: "LOYALTY_ROI", path: "loyalty-roi", title: "Loyalty Roi", category: "Customer Experience", icon: "heart" },
  { name: "LOYALTY_TIER_MIGRATION", path: "loyalty-tier-migration", title: "Loyalty Tier Migration", category: "Customer Experience", icon: "heart" },
  { name: "MILESTONE_CAMPAIGN", path: "milestone-campaign", title: "Milestone Campaign", category: "Customer Experience", icon: "heart" },
  { name: "OVERBOOKING", path: "overbooking", title: "Overbooking", category: "Customer Experience", icon: "heart" },
  { name: "PREFERENCE_DRIFT", path: "preference-drift", title: "Preference Drift", category: "Customer Experience", icon: "heart" },
  { name: "RESERVATION_CASCADE", path: "reservation-cascade", title: "Reservation Cascade", category: "Customer Experience", icon: "heart" },
  { name: "RETENTION_PROGRAM", path: "retention-program", title: "Retention Program", category: "Customer Experience", icon: "heart" },
  { name: "REVIEW_RESPONSE", path: "review-response", title: "Review Response", category: "Customer Experience", icon: "heart" },
  { name: "SEATING_COMFORT_FURNITURE", path: "seating-comfort-furniture", title: "Seating Comfort Furniture", category: "Customer Experience", icon: "heart" },
  { name: "SEATING_OPTIMIZATION", path: "seating-optimization", title: "Seating Optimization", category: "Customer Experience", icon: "heart" },
  { name: "SEGMENTATION", path: "segmentation", title: "Segmentation", category: "Customer Experience", icon: "heart" },
  { name: "SENTIMENT", path: "sentiment", title: "Sentiment", category: "Customer Experience", icon: "heart" },
  { name: "SENTIMENT_HEATMAP", path: "sentiment-heatmap", title: "Sentiment Heatmap", category: "Customer Experience", icon: "heart" },
  { name: "SENTIMENT_TREND", path: "sentiment-trend", title: "Sentiment Trend", category: "Customer Experience", icon: "heart" },
  { name: "SERVER_TABLE_ASSIGNMENT", path: "server-table-assignment", title: "Server Table Assignment", category: "Customer Experience", icon: "heart" },
  { name: "TABLE_PREFERENCE", path: "table-preference", title: "Table Preference", category: "Customer Experience", icon: "heart" },
  { name: "TABLE_SETTING_TABLEWARE", path: "table-setting-tableware", title: "Table Setting Tableware", category: "Customer Experience", icon: "heart" },
  { name: "TABLE_UTILIZATION", path: "table-utilization", title: "Table Utilization", category: "Customer Experience", icon: "heart" },
  { name: "TABLES_SUMMARY", path: "tables-summary", title: "Tables Summary", category: "Customer Experience", icon: "heart" },
  { name: "TABLETOP_ENTERTAINMENT_ACTIVITY", path: "tabletop-entertainment-activity", title: "Tabletop Entertainment Activity", category: "Customer Experience", icon: "heart" },
  { name: "VISIT_CADENCE", path: "visit-cadence", title: "Visit Cadence", category: "Customer Experience", icon: "heart" },
  { name: "WAIT_EXPERIENCE", path: "wait-experience", title: "Wait Experience", category: "Customer Experience", icon: "heart" },
  { name: "WAITLIST_OPTIMIZER", path: "waitlist-optimizer", title: "Waitlist Optimizer", category: "Customer Experience", icon: "heart" },
  { name: "DELIVERY_ANALYTICS", path: "delivery-analytics", title: "Delivery Analytics", category: "Delivery & Logistics", icon: "truckFast" },
  { name: "DELIVERY_DENSITY", path: "delivery-density", title: "Delivery Density", category: "Delivery & Logistics", icon: "truckFast" },
  { name: "DELIVERY_QUALITY_DECAY", path: "delivery-quality-decay", title: "Delivery Quality Decay", category: "Delivery & Logistics", icon: "truckFast" },
  { name: "DELIVERY_ROUTE", path: "delivery-route", title: "Delivery Route", category: "Delivery & Logistics", icon: "truckFast" },
  { name: "DELIVERY_ZONE_OPTIMIZER", path: "delivery-zone-optimizer", title: "Delivery Zone Optimizer", category: "Delivery & Logistics", icon: "truckFast" },
  { name: "DRONE_DELIVERY_AERIAL_LOGISTICS", path: "drone-delivery-aerial-logistics", title: "Drone Delivery Aerial Logistics", category: "Delivery & Logistics", icon: "truckFast" },
  { name: "ATMOSPHERE_REVENUE", path: "atmosphere-revenue", title: "Atmosphere Revenue", category: "Finance & Sales", icon: "dollarSign" },
  { name: "CASH_CLOSING", path: "cash-closing", title: "Cash Closing", category: "Finance & Sales", icon: "dollarSign" },
  { name: "CASH_DRAWER_ANOMALY", path: "cash-drawer-anomaly", title: "Cash Drawer Anomaly", category: "Finance & Sales", icon: "dollarSign" },
  { name: "CASH_EARLY_WARNING", path: "cash-early-warning", title: "Cash Early Warning", category: "Finance & Sales", icon: "dollarSign" },
  { name: "CASH_FLOW", path: "cash-flow", title: "Cash Flow", category: "Finance & Sales", icon: "dollarSign" },
  { name: "CASH_STRESS_TEST", path: "cash-stress-test", title: "Cash Stress Test", category: "Finance & Sales", icon: "dollarSign" },
  { name: "CHARGEBACK_RISK", path: "chargeback-risk", title: "Chargeback Risk", category: "Finance & Sales", icon: "dollarSign" },
  { name: "COUPON", path: "coupon", title: "Coupon", category: "Finance & Sales", icon: "dollarSign" },
  { name: "DATA_MONETIZATION_API_REVENUE", path: "data-monetization-api-revenue", title: "Data Monetization Api Revenue", category: "Finance & Sales", icon: "dollarSign" },
  { name: "DISCOUNTS", path: "discounts", title: "Discounts", category: "Finance & Sales", icon: "dollarSign" },
  { name: "DYNAMIC_PRICING", path: "dynamic-pricing", title: "Dynamic Pricing", category: "Finance & Sales", icon: "dollarSign" },
  { name: "ELASTICITY_DRIFT", path: "elasticity-drift", title: "Elasticity Drift", category: "Finance & Sales", icon: "dollarSign" },
  { name: "EXPENSE", path: "expense", title: "Expense", category: "Finance & Sales", icon: "dollarSign" },
  { name: "GIFTCARD_FRAUD", path: "giftcard-fraud", title: "Giftcard Fraud", category: "Finance & Sales", icon: "dollarSign" },
  { name: "MAINTENANCE_BUDGET", path: "maintenance-budget", title: "Maintenance Budget", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PAYMENT_FEE_OPTIMIZER", path: "payment-fee-optimizer", title: "Payment Fee Optimizer", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PEAK_PRICING", path: "peak-pricing", title: "Peak Pricing", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PRICE_AB_TESTING", path: "price-ab-testing", title: "Price Ab Testing", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PRICE_ELASTICITY", path: "price-elasticity", title: "Price Elasticity", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PRICE_PSYCHOLOGY", path: "price-psychology", title: "Price Psychology", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PROFITABILITY_DECAY", path: "profitability-decay", title: "Profitability Decay", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PROMO_ABUSE", path: "promo-abuse", title: "Promo Abuse", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PROMO_EFFECTIVENESS", path: "promo-effectiveness", title: "Promo Effectiveness", category: "Finance & Sales", icon: "dollarSign" },
  { name: "PROMO_HALO_EFFECT", path: "promo-halo-effect", title: "Promo Halo Effect", category: "Finance & Sales", icon: "dollarSign" },
  { name: "REFUND_ABUSE", path: "refund-abuse", title: "Refund Abuse", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALE_VS_CONSUMPTION", path: "sale-vs-consumption", title: "Sale Vs Consumption", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALES_ADVANCED", path: "sales-advanced", title: "Sales Advanced", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALES_DASHBOARD", path: "sales-dashboard", title: "Sales Dashboard", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALES_HOURLY_LABOUR", path: "sales-hourly-labour", title: "Sales Hourly Labour", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALES_HOURLY_LABOUR_WEEKLY", path: "sales-hourly-labour-weekly", title: "Sales Hourly Labour Weekly", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALES_SERVER", path: "sales-server", title: "Sales Server", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALES_SUMMARY", path: "sales-summary", title: "Sales Summary", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALES_SUMMARY2", path: "sales-summary-2", title: "Sales Summary2", category: "Finance & Sales", icon: "dollarSign" },
  { name: "SALES_WEEKLY", path: "sales-weekly", title: "Sales Weekly", category: "Finance & Sales", icon: "dollarSign" },
  { name: "TAX", path: "tax", title: "Tax", category: "Finance & Sales", icon: "dollarSign" },
  { name: "TAX_DEDUCTION_FINDER", path: "tax-deduction-finder", title: "Tax Deduction Finder", category: "Finance & Sales", icon: "dollarSign" },
  { name: "TIP_ANALYTICS", path: "tip-analytics", title: "Tip Analytics", category: "Finance & Sales", icon: "dollarSign" },
  { name: "TIPS", path: "tips", title: "Tips", category: "Finance & Sales", icon: "dollarSign" },
  { name: "UTILITY_BILL_OPTIMIZER", path: "utility-bill-optimizer", title: "Utility Bill Optimizer", category: "Finance & Sales", icon: "dollarSign" },
  { name: "VENDOR_INVOICE_AUDIT", path: "vendor-invoice-audit", title: "Vendor Invoice Audit", category: "Finance & Sales", icon: "dollarSign" },
  { name: "CURRENT_INVENTORY", path: "current-inventory", title: "Current Inventory", category: "Inventory & Suppliers", icon: "boxesStacked" },
  { name: "DETAILED_INVENTORY", path: "detailed-inventory", title: "Detailed Inventory", category: "Inventory & Suppliers", icon: "boxesStacked" },
  { name: "INVENTORY_DASHBOARD", path: "inventory-dashboard", title: "Inventory Dashboard", category: "Inventory & Suppliers", icon: "boxesStacked" },
  { name: "INVENTORY_TRANSFER", path: "inventory-transfer", title: "Inventory Transfer", category: "Inventory & Suppliers", icon: "boxesStacked" },
  { name: "SUPPLIER_NEGOTIATION", path: "supplier-negotiation", title: "Supplier Negotiation", category: "Inventory & Suppliers", icon: "boxesStacked" },
  { name: "FOOD_DISPLAY_PASTRY_CASE", path: "food-display-pastry-case", title: "Food Display Pastry Case", category: "Kitchen Operations", icon: "fire" },
  { name: "GHOST_KITCHEN_VIRTUAL_BRAND", path: "ghost-kitchen-virtual-brand", title: "Ghost Kitchen Virtual Brand", category: "Kitchen Operations", icon: "fire" },
  { name: "KITCHEN_BOTTLENECK", path: "kitchen-bottleneck", title: "Kitchen Bottleneck", category: "Kitchen Operations", icon: "fire" },
  { name: "KITCHEN_RECONCILIATION", path: "kitchen-reconciliation", title: "Kitchen Reconciliation", category: "Kitchen Operations", icon: "fire" },
  { name: "KITCHEN_ROBOTICS_AUTOMATION", path: "kitchen-robotics-automation", title: "Kitchen Robotics Automation", category: "Kitchen Operations", icon: "fire" },
  { name: "KITCHEN_STATION_EFFICIENCY", path: "kitchen-station-efficiency", title: "Kitchen Station Efficiency", category: "Kitchen Operations", icon: "fire" },
  { name: "PREP_SHEET_OPTIMIZER", path: "prep-sheet-optimizer", title: "Prep Sheet Optimizer", category: "Kitchen Operations", icon: "fire" },
  { name: "WATER_STATION_BEVERAGE_BAR", path: "water-station-beverage-bar", title: "Water Station Beverage Bar", category: "Kitchen Operations", icon: "fire" },
  { name: "3D_FOOD_PRINTING_CUSTOMIZED_CUISINE", path: "3d-food-printing-customized-cuisine", title: "3D Food Printing Customized Cuisine", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "ABANDONED_CART", path: "abandoned-cart", title: "Abandoned Cart", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "AD_ROI_TRACKER", path: "ad-roi-tracker", title: "Ad Roi Tracker", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "AD_TARGETING", path: "ad-targeting", title: "Ad Targeting", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "AIR_QUALITY_VENTILATION", path: "air-quality-ventilation", title: "Air Quality Ventilation", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "BIOPHILIC_DESIGN_PLANT", path: "biophilic-design-plant", title: "Biophilic Design Plant", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "BRANDED_MERCH_RETAIL", path: "branded-merchandise-retail", title: "Branded Merch Retail", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "CARBON_FOOTPRINT_TRACKER", path: "carbon-footprint-tracker", title: "Carbon Footprint Tracker", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "CATERING_OPTIMIZER", path: "catering-optimizer", title: "Catering Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "CEILING_DESIGN_DECOR", path: "ceiling-design-decor", title: "Ceiling Design Decor", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "CELEBRATION_SERVICE_OPTIMIZER", path: "celebration-service-optimizer", title: "Celebration Service Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "COAT_CHECK_CLOAKROOM", path: "coat-check-cloakroom", title: "Coat Check Cloakroom", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "COLOR_SCHEME_PALETTE", path: "color-scheme-palette", title: "Color Scheme Palette", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "COMMUNITY_PARTNERSHIP_ENGAGEMENT", path: "community-partnership-engagement", title: "Community Partnership Engagement", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "COMPETITOR_INTELLIGENCE", path: "competitor-intelligence", title: "Competitor Intelligence", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "COMPETITOR_MONITORING", path: "competitor-monitoring", title: "Competitor Monitoring", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "CURB_APPEAL_FACADE", path: "curb-appeal-facade", title: "Curb Appeal Facade", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "DRIVE_THRU_PICKUP_WINDOW", path: "drive-thru-pickup-window", title: "Drive Thru Pickup Window", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "ENTRANCE_ARRIVAL_OPTIMIZER", path: "entrance-arrival-optimizer", title: "Entrance Arrival Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "FAMILY_INFANT_AMENITY", path: "family-infant-amenity", title: "Family Infant Amenity", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "FIREPLACE_FIRE_FEATURE", path: "fireplace-fire-feature", title: "Fireplace Fire Feature", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "FLOOR_CEILING_SURFACE", path: "floor-ceiling-surface", title: "Floor Ceiling Surface", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "FLOOR_PLAN_OPTIMIZER", path: "floor-plan-optimizer", title: "Floor Plan Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "GREEN_CERTIFICATION_ECO", path: "green-certification-eco", title: "Green Certification Eco", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "HEALTH_INSPECTION_READINESS", path: "health-inspection-readiness", title: "Health Inspection Readiness", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "INFLUENCER_OUTREACH_OPTIMIZER", path: "influencer-outreach-optimizer", title: "Influencer Outreach Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "INTERIOR_SIGNAGE_WAYFINDING", path: "interior-signage-wayfinding", title: "Interior Signage Wayfinding", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "LIGHTING_MOOD_OPTIMIZER", path: "lighting-mood-optimizer", title: "Lighting Mood Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "LOCAL_SEO", path: "local-seo", title: "Local Seo", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "METAVERSE_VIRTUAL_RESTAURANT_DINING", path: "metaverse-virtual-restaurant-dining", title: "Metaverse Virtual Restaurant Dining", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "MIRROR_REFLECTIVE_SURFACE", path: "mirror-reflective-surface", title: "Mirror Reflective Surface", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "MOBILE_APP_ORDERING", path: "mobile-app-ordering", title: "Mobile App Ordering", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "NEURO_EMOTION_BIOMETRIC_DINING", path: "neuro-emotion-biometric-dining", title: "Neuro Emotion Biometric Dining", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "NOISE_ACOUSTIC_COMFORT", path: "noise-acoustic-comfort", title: "Noise Acoustic Comfort", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "ON_SITE_FARM_HYPERLOCAL_AGRICULTURE", path: "on-site-farm-hyperlocal-agriculture", title: "On Site Farm Hyperlocal Agriculture", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "OUTDOOR_LANDSCAPE_LIGHTING", path: "outdoor-landscape-lighting", title: "Outdoor Landscape Lighting", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "OUTDOOR_PATIO_SEASONAL", path: "outdoor-patio-seasonal", title: "Outdoor Patio Seasonal", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "PARKING_LOT_OPTIMIZER", path: "parking-lot-optimizer", title: "Parking Lot Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "PEAK_HOUR", path: "peak-hour", title: "Peak Hour", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "PET_FRIENDLY_SERVICE_ANIMAL", path: "pet-friendly-service-animal", title: "Pet Friendly Service Animal", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "PHONE_CHARGING_POWER", path: "phone-charging-power", title: "Phone Charging Power", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "PRIVATE_EVENT_SPACE", path: "private-event-space", title: "Private Event Space", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "QUANTUM_COMPUTING_RESTAURANT_OPTIMIZATION", path: "quantum-computing-restaurant-optimization", title: "Quantum Computing Restaurant Optimization", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "RESTROOM_CLEANLINESS", path: "restroom-cleanliness", title: "Restroom Cleanliness", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "RESTROOM_DESIGN_FIXTURE", path: "restroom-design-fixture", title: "Restroom Design Fixture", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "ROOM_PARTITION_DIVIDER", path: "room-partition-divider", title: "Room Partition Divider", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "ROTATING_ART_GALLERY", path: "rotating-art-gallery", title: "Rotating Art Gallery", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SCENT_MARKETING_OPTIMIZER", path: "scent-marketing-optimizer", title: "Scent Marketing Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SEASONAL_HOLIDAY_DECOR", path: "seasonal-holiday-decor", title: "Seasonal Holiday Decor", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SEASONAL_TRENDS", path: "seasonal-trends", title: "Seasonal Trends", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SELF_SERVICE_KIOSK_TERMINAL", path: "self-service-kiosk-terminal", title: "Self Service Kiosk Terminal", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SENSORY_FRIENDLY_SPACE", path: "sensory-friendly-space", title: "Sensory Friendly Space", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SERVER_LOAD_BALANCER", path: "server-load-balancer", title: "Server Load Balancer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SMART_RESTAURANT_IOT_CONNECTED_DEVICE", path: "smart-restaurant-iot-connected-device", title: "Smart Restaurant Iot Connected Device", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SOCIAL_CONTENT", path: "social-content", title: "Social Content", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SOCIAL_LISTENING", path: "social-listening", title: "Social Listening", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "SOUND_SYSTEM_SPEAKER", path: "sound-system-speaker", title: "Sound System Speaker", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "TEMPERATURE_HVAC_COMFORT", path: "temperature-hvac-comfort", title: "Temperature Hvac Comfort", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "VIBE_OPTIMIZER", path: "vibe-optimizer", title: "Vibe Optimizer", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "WALL_DECOR_ARTWORK", path: "wall-decor-artwork", title: "Wall Decor Artwork", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "WASTE", path: "waste", title: "Waste", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "WASTE_INTELLIGENCE", path: "waste-intelligence", title: "Waste Intelligence", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "WASTE_TO_VALUE", path: "waste-to-value", title: "Waste To Value", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "WEATHER_IMPACT", path: "weather-impact", title: "Weather Impact", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "WIFI_EXPERIENCE", path: "wifi-experience", title: "Wifi Experience", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "WINDOW_NATURAL_LIGHT", path: "window-natural-light", title: "Window Natural Light", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "WINDOW_TREATMENT_CURTAIN", path: "window-treatment-curtain", title: "Window Treatment Curtain", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "ZERO_WASTE_CIRCULAR_ECONOMY", path: "zero-waste-circular-economy", title: "Zero Waste Circular Economy", category: "Marketing & Experience", icon: "bullhorn" },
  { name: "ACCESSIBILITY_MENU_ADA", path: "accessibility-menu-ada", title: "Accessibility Menu Ada", category: "Menu & Recipes", icon: "utensils" },
  { name: "AR_MENU_IMMERSIVE_DINING", path: "ar-menu-immersive-dining", title: "Ar Menu Immersive Dining", category: "Menu & Recipes", icon: "utensils" },
  { name: "DIGITAL_MENU_QR", path: "digital-menu-qr", title: "Digital Menu Qr", category: "Menu & Recipes", icon: "utensils" },
  { name: "DISH_POPULARITY", path: "dish-popularity", title: "Dish Popularity", category: "Menu & Recipes", icon: "utensils" },
  { name: "DISH_PROFITABILITY", path: "dish-profitability", title: "Dish Profitability", category: "Menu & Recipes", icon: "utensils" },
  { name: "EVENT_MENU", path: "event-menu", title: "Event Menu", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_CANNIBALIZATION", path: "menu-cannibalization", title: "Menu Cannibalization", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_DESCRIPTION", path: "menu-description", title: "Menu Description", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_ENGINEERING_MATRIX", path: "menu-engineering-matrix", title: "Menu Engineering Matrix", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_ITEM_RETIREMENT", path: "menu-item-retirement", title: "Menu Item Retirement", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_LAYOUT_PLACEMENT", path: "menu-layout-placement", title: "Menu Layout Placement", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_OPTIMIZATION", path: "menu-optimization", title: "Menu Optimization", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_PAIRING", path: "menu-pairing", title: "Menu Pairing", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_PHOTOGRAPHY", path: "menu-photography", title: "Menu Photography", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_ROTATION", path: "menu-rotation", title: "Menu Rotation", category: "Menu & Recipes", icon: "utensils" },
  { name: "MENU_TYPOGRAPHY_MATERIAL", path: "menu-typography-material", title: "Menu Typography Material", category: "Menu & Recipes", icon: "utensils" },
  { name: "MUSIC_PLAYLIST_ROTATION", path: "music-playlist-rotation", title: "Music Playlist Rotation", category: "Menu & Recipes", icon: "utensils" },
  { name: "NUTRITIONAL_TRANSPARENCY", path: "nutritional-transparency", title: "Nutritional Transparency", category: "Menu & Recipes", icon: "utensils" },
  { name: "PAIRING_AFFINITY", path: "pairing-affinity", title: "Pairing Affinity", category: "Menu & Recipes", icon: "utensils" },
  { name: "PERSONALIZED_NUTRITION_DNA_GENOMIC_DINING", path: "personalized-nutrition-dna-genomic-dining", title: "Personalized Nutrition Dna Genomic Dining", category: "Menu & Recipes", icon: "utensils" },
  { name: "RECIPE_NUTRITION_GENERATOR", path: "recipe-nutrition-generator", title: "Recipe Nutrition Generator", category: "Menu & Recipes", icon: "utensils" },
  { name: "RECIPE_OPTIMIZATION", path: "recipe-optimization", title: "Recipe Optimization", category: "Menu & Recipes", icon: "utensils" },
  { name: "RECIPE_SCALING", path: "recipe-scaling", title: "Recipe Scaling", category: "Menu & Recipes", icon: "utensils" },
  { name: "RECIPE_SUBSTITUTION", path: "recipe-substitution", title: "Recipe Substitution", category: "Menu & Recipes", icon: "utensils" },
  { name: "SUBSTITUTION_IMPACT", path: "substitution-impact", title: "Substitution Impact", category: "Menu & Recipes", icon: "utensils" },
  { name: "WINE_PAIRING", path: "wine-pairing", title: "Wine Pairing", category: "Menu & Recipes", icon: "utensils" },
  { name: "BRANCH_COMPARISON", path: "branch-comparison", title: "Branch Comparison", category: "Multi-Location", icon: "building" },
  { name: "FRANCHISE_MULTI_UNIT_OPERATIONS", path: "franchise-multi-unit-operations", title: "Franchise Multi Unit Operations", category: "Multi-Location", icon: "building" },
  { name: "MULTI_LOCATION_BENCHMARK", path: "multi-location-benchmark", title: "Multi Location Benchmark", category: "Multi-Location", icon: "building" },
  { name: "MERGE_ORDERS", path: "merge-orders", title: "Merge Orders", category: "Orders & POS", icon: "cashRegister" },
  { name: "ORDER_CUSTOMIZATION_ANALYZER", path: "order-customization-analyzer", title: "Order Customization Analyzer", category: "Orders & POS", icon: "cashRegister" },
  { name: "ORDER_FREQUENCY", path: "order-frequency", title: "Order Frequency", category: "Orders & POS", icon: "cashRegister" },
  { name: "ORDER_LIFECYCLE", path: "order-lifecycle", title: "Order Lifecycle", category: "Orders & POS", icon: "cashRegister" },
  { name: "ORDER_MODIFICATION_PATTERN", path: "order-modification-pattern", title: "Order Modification Pattern", category: "Orders & POS", icon: "cashRegister" },
  { name: "ORDER_PACING", path: "order-pacing", title: "Order Pacing", category: "Orders & POS", icon: "cashRegister" },
  { name: "ORDER_RECEIPT", path: "order-receipt", title: "Order Receipt", category: "Orders & POS", icon: "cashRegister" },
  { name: "PHONE_ORDER_OPTIMIZER", path: "phone-order-optimizer", title: "Phone Order Optimizer", category: "Orders & POS", icon: "cashRegister" },
  { name: "PURCHASE_ORDER", path: "purchase-order", title: "Purchase Order", category: "Orders & POS", icon: "cashRegister" },
  { name: "SPLIT_ORDERS", path: "split-orders", title: "Split Orders", category: "Orders & POS", icon: "cashRegister" },
  { name: "TICKET_COMPLEXITY", path: "ticket-complexity", title: "Ticket Complexity", category: "Orders & POS", icon: "cashRegister" },
  { name: "VOICE_ORDERING_CONVERSATIONAL_AI", path: "voice-ordering-conversational-ai", title: "Voice Ordering Conversational Ai", category: "Orders & POS", icon: "cashRegister" },
  { name: "ACTIVITY", path: "activity", title: "Activity", category: "Other Reports", icon: "chartBar" },
  { name: "AI", path: "ai", title: "Ai", category: "Other Reports", icon: "chartBar" },
  { name: "AI_COMMAND_CENTER", path: "ai-command-center", title: "Ai Command Center", category: "Other Reports", icon: "chartBar" },
  { name: "AUDIT", path: "audit", title: "Audit", category: "Other Reports", icon: "chartBar" },
  { name: "BAR_POUR_VARIANCE", path: "bar-pour-variance", title: "Bar Pour Variance", category: "Other Reports", icon: "chartBar" },
  { name: "COMPENSATION_OPTIMIZER", path: "compensation-optimizer", title: "Compensation Optimizer", category: "Other Reports", icon: "chartBar" },
  { name: "COMPLAINT_PATTERN", path: "complaint-pattern", title: "Complaint Pattern", category: "Other Reports", icon: "chartBar" },
  { name: "CONSUMPTION", path: "consumption", title: "Consumption", category: "Other Reports", icon: "chartBar" },
  { name: "CRISIS_COMMUNICATION_PR_REPUTATION", path: "crisis-communication-pr-reputation", title: "Crisis Communication Pr Reputation", category: "Other Reports", icon: "chartBar" },
  { name: "CROSS_CHANNEL_ATTRIBUTION", path: "cross-channel-attribution", title: "Cross Channel Attribution", category: "Other Reports", icon: "chartBar" },
  { name: "CROSS_SELL", path: "cross-sell", title: "Cross Sell", category: "Other Reports", icon: "chartBar" },
  { name: "CULINARY_EXPERIENCE_COOKING_CLASS", path: "culinary-experience-cooking-class", title: "Culinary Experience Cooking Class", category: "Other Reports", icon: "chartBar" },
  { name: "EQUIPMENT_MAINTENANCE", path: "equipment-maintenance", title: "Equipment Maintenance", category: "Other Reports", icon: "chartBar" },
  { name: "FOOD_COST_TRENDS", path: "food-cost-trends", title: "Food Cost Trends", category: "Other Reports", icon: "chartBar" },
  { name: "ISSUE", path: "issue", title: "Issue", category: "Other Reports", icon: "chartBar" },
  { name: "ISSUE_RETURN", path: "issue-return", title: "Issue Return", category: "Other Reports", icon: "chartBar" },
  { name: "OPENING_CLOSING_AUTOMATOR", path: "opening-closing-automator", title: "Opening Closing Automator", category: "Other Reports", icon: "chartBar" },
  { name: "PACKAGING_OPTIMIZER", path: "packaging-optimizer", title: "Packaging Optimizer", category: "Other Reports", icon: "chartBar" },
  { name: "PRODUCT_HOURLY", path: "product-hourly", title: "Product Hourly", category: "Other Reports", icon: "chartBar" },
  { name: "PRODUCT_LIST", path: "product-list", title: "Product List", category: "Other Reports", icon: "chartBar" },
  { name: "PRODUCT_MIX_SUMMARY", path: "product-mix-summary", title: "Product Mix Summary", category: "Other Reports", icon: "chartBar" },
  { name: "PRODUCT_MIX_WEEKLY", path: "product-mix-weekly", title: "Product Mix Weekly", category: "Other Reports", icon: "chartBar" },
  { name: "PRODUCTION", path: "production", title: "Production", category: "Other Reports", icon: "chartBar" },
  { name: "PURCHASE", path: "purchase", title: "Purchase", category: "Other Reports", icon: "chartBar" },
  { name: "PURCHASE_RETURN", path: "purchase-return", title: "Purchase Return", category: "Other Reports", icon: "chartBar" },
  { name: "REVPASH", path: "revpash", title: "Revpash", category: "Other Reports", icon: "chartBar" },
  { name: "SCHEDULING_OPTIMIZATION", path: "scheduling-optimization", title: "Scheduling Optimization", category: "Other Reports", icon: "chartBar" },
  { name: "SUBSCRIPTION_MEMBERSHIP_PROGRAM", path: "subscription-membership-program", title: "Subscription Membership Program", category: "Other Reports", icon: "chartBar" },
  { name: "TAKEOUT_PACKAGING_CONTAINER", path: "takeout-packaging-container", title: "Takeout Packaging Container", category: "Other Reports", icon: "chartBar" },
  { name: "UPSELL_EFFECTIVENESS", path: "upsell-effectiveness", title: "Upsell Effectiveness", category: "Other Reports", icon: "chartBar" },
  { name: "VOIDS", path: "voids", title: "Voids", category: "Other Reports", icon: "chartBar" },
  { name: "WIN_BACK", path: "win-back", title: "Win Back", category: "Other Reports", icon: "chartBar" },
  { name: "BREAK_COMPLIANCE", path: "break-compliance", title: "Break Compliance", category: "Staff & HR", icon: "users" },
  { name: "BREAK_EVEN_TRACKER", path: "break-even-tracker", title: "Break Even Tracker", category: "Staff & HR", icon: "users" },
  { name: "CLEANING_SCHEDULER", path: "cleaning-scheduler", title: "Cleaning Scheduler", category: "Staff & HR", icon: "users" },
  { name: "DRIVER_COACH", path: "driver-coach", title: "Driver Coach", category: "Staff & HR", icon: "users" },
  { name: "ENERGY_OPTIMIZATION", path: "energy-optimization", title: "Energy Optimization", category: "Staff & HR", icon: "users" },
  { name: "ENERGY_VAMPIRE", path: "energy-vampire", title: "Energy Vampire", category: "Staff & HR", icon: "users" },
  { name: "KITCHEN_PREP_SCHEDULER", path: "kitchen-prep-scheduler", title: "Kitchen Prep Scheduler", category: "Staff & HR", icon: "users" },
  { name: "KITCHEN_SKILL_GAP", path: "kitchen-skill-gap", title: "Kitchen Skill Gap", category: "Staff & HR", icon: "users" },
  { name: "LABOR_ABSENCE", path: "labor-absence", title: "Labor Absence", category: "Staff & HR", icon: "users" },
  { name: "LABOR_ATTENDANCE", path: "labor-attendance", title: "Labor Attendance", category: "Staff & HR", icon: "users" },
  { name: "LABOR_COST_CENTER_COST", path: "labor-cost-center-cost", title: "Labor Cost Center Cost", category: "Staff & HR", icon: "users" },
  { name: "LABOR_DAILY_COST", path: "labor-daily-cost", title: "Labor Daily Cost", category: "Staff & HR", icon: "users" },
  { name: "LABOR_DASHBOARD", path: "labor-dashboard", title: "Labor Dashboard", category: "Staff & HR", icon: "users" },
  { name: "LABOR_DEPARTMENT_COST", path: "labor-department-cost", title: "Labor Department Cost", category: "Staff & HR", icon: "users" },
  { name: "LABOR_EMPLOYEE_COST", path: "labor-employee-cost", title: "Labor Employee Cost", category: "Staff & HR", icon: "users" },
  { name: "LABOR_HOLIDAY_COST", path: "labor-holiday-cost", title: "Labor Holiday Cost", category: "Staff & HR", icon: "users" },
  { name: "LABOR_LATE_ARRIVAL", path: "labor-late-arrival", title: "Labor Late Arrival", category: "Staff & HR", icon: "users" },
  { name: "LABOR_LEAVE", path: "labor-leave", title: "Labor Leave", category: "Staff & HR", icon: "users" },
  { name: "LABOR_MANAGER_APPROVAL", path: "labor-manager-approval", title: "Labor Manager Approval", category: "Staff & HR", icon: "users" },
  { name: "LABOR_MONTHLY_COST", path: "labor-monthly-cost", title: "Labor Monthly Cost", category: "Staff & HR", icon: "users" },
  { name: "LABOR_OPTIMIZATION", path: "labor-optimization", title: "Labor Optimization", category: "Staff & HR", icon: "users" },
  { name: "LABOR_OVERTIME", path: "labor-overtime", title: "Labor Overtime", category: "Staff & HR", icon: "users" },
  { name: "LABOR_PAYROLL_DETAILS", path: "labor-payroll-details", title: "Labor Payroll Details", category: "Staff & HR", icon: "users" },
  { name: "LABOR_PAYROLL_SUMMARY", path: "labor-payroll-summary", title: "Labor Payroll Summary", category: "Staff & HR", icon: "users" },
  { name: "LABOR_SCHEDULE_ROSTER", path: "labor-schedule-roster", title: "Labor Schedule Roster", category: "Staff & HR", icon: "users" },
  { name: "LABOR_SCHEDULED_VS_ACTUAL", path: "labor-scheduled-vs-actual", title: "Labor Scheduled Vs Actual", category: "Staff & HR", icon: "users" },
  { name: "LABOR_TREND", path: "labor-trend", title: "Labor Trend", category: "Staff & HR", icon: "users" },
  { name: "LABOR_WEEKLY_COST", path: "labor-weekly-cost", title: "Labor Weekly Cost", category: "Staff & HR", icon: "users" },
  { name: "LIVE_MUSIC_PERFORMANCE", path: "live-music-performance", title: "Live Music Performance", category: "Staff & HR", icon: "users" },
  { name: "PRE_SHIFT_BRIEFING", path: "pre-shift-briefing", title: "Pre Shift Briefing", category: "Staff & HR", icon: "users" },
  { name: "SCHEDULE_CONFLICT_RESOLVER", path: "schedule-conflict-resolver", title: "Schedule Conflict Resolver", category: "Staff & HR", icon: "users" },
  { name: "SCHEDULE_PREFERENCE", path: "schedule-preference", title: "Schedule Preference", category: "Staff & HR", icon: "users" },
  { name: "SERVER_COACH", path: "server-coach", title: "Server Coach", category: "Staff & HR", icon: "users" },
  { name: "SERVER_PERFORMANCE", path: "server-performance", title: "Server Performance", category: "Staff & HR", icon: "users" },
  { name: "SHIFT_HANDOVER", path: "shift-handover", title: "Shift Handover", category: "Staff & HR", icon: "users" },
  { name: "STAFF_APPEARANCE_UNIFORM", path: "staff-appearance-uniform", title: "Staff Appearance Uniform", category: "Staff & HR", icon: "users" },
  { name: "STAFF_ENERGY", path: "staff-energy", title: "Staff Energy", category: "Staff & HR", icon: "users" },
  { name: "STAFF_GAMIFICATION", path: "staff-gamification", title: "Staff Gamification", category: "Staff & HR", icon: "users" },
  { name: "STAFF_MENTAL_HEALTH_WELLNESS", path: "staff-mental-health-wellness", title: "Staff Mental Health Wellness", category: "Staff & HR", icon: "users" },
  { name: "STAFF_TURNOVER", path: "staff-turnover", title: "Staff Turnover", category: "Staff & HR", icon: "users" },
  { name: "TABLE_TURNOVER", path: "table-turnover", title: "Table Turnover", category: "Staff & HR", icon: "users" },
  { name: "TABLE_TURNOVER_VELOCITY", path: "table-turnover-velocity", title: "Table Turnover Velocity", category: "Staff & HR", icon: "users" },
  { name: "TRAINING_NEED", path: "training-need", title: "Training Need", category: "Staff & HR", icon: "users" },
  { name: "VENDOR_PERFORMANCE", path: "vendor-performance", title: "Vendor Performance", category: "Staff & HR", icon: "users" },
];

export const FEATURE_HUB_CATEGORIES = [
  { name: "AI Forecasting", count: 30 },
  { name: "Compliance & Safety", count: 9 },
  { name: "Customer Experience", count: 29 },
  { name: "Delivery & Logistics", count: 6 },
  { name: "Finance & Sales", count: 40 },
  { name: "Inventory & Suppliers", count: 5 },
  { name: "Kitchen Operations", count: 8 },
  { name: "Marketing & Experience", count: 68 },
  { name: "Menu & Recipes", count: 26 },
  { name: "Multi-Location", count: 3 },
  { name: "Orders & POS", count: 12 },
  { name: "Other Reports", count: 32 },
  { name: "Staff & HR", count: 44 },
];
