export const LOGIN = '/';
export const MENU = '/menu';
export const ORDERS = '/orders';
export const SUMMARY = '/summary';
export const KITCHEN = '/kitchen';
export const ORDER_DISPLAY = '/order-display';
export const DELIVERY = '/delivery';
export const CLOSING = '/closing';
export const ADMIN = '/admin';
export const SETTINGS = '/settings';
export const INTEGRATIONS = '/integrations';
export const CLOCK = '/clock';
export const TABLESIDE = '/tableside';
export const INVENTORY = '/inventory';
export const INVENTORY_PRINT = '/inventory/print/:type/:id';

export type InventoryPrintDocType =
  | 'purchase'
  | 'purchase-return'
  | 'purchase-order'
  | 'issue'
  | 'issue-return'
  | 'waste'
  | 'stock-transfer';

export const inventoryPrintUrl = (type: InventoryPrintDocType, id: string | {toString(): string}) => {
  const raw = typeof id === 'string' ? id : id.toString();
  const encodedId = encodeURIComponent(raw);
  return `/inventory/print/${type}/${encodedId}`;
};
export const HR = '/hr';
export const TIP_DISTRIBUTION = '/tip-distribution';
export const ACCOUNTS = '/accounts';

export const REPORTS = '/reports';
export const REPORTS_PRODUCT_MIX_WEEKLY = REPORTS + '/product-mix-weekly';
export const REPORTS_SALES_DASHBOARD = REPORTS + '/sales-dashboard';
export const REPORTS_INVENTORY_DASHBOARD = REPORTS + '/inventory-dashboard';
export const REPORTS_AUDIT = REPORTS + '/audit';
export const REPORTS_CASH_CLOSING = REPORTS + '/cash-closing';
export const REPORTS_DISCOUNTS = REPORTS + '/discounts';
export const REPORTS_TAX = REPORTS + '/tax';
export const REPORTS_COUPON = REPORTS + '/coupon';
export const REPORTS_MERGE_ORDERS = REPORTS + '/merge-orders';
export const REPORTS_SPLIT_ORDERS = REPORTS + '/split-orders';
export const REPORTS_ORDER_LIFECYCLE = REPORTS + '/order-lifecycle';
export const REPORTS_ORDER_RECEIPT = REPORTS + '/order-receipt';
export const REPORTS_ORDER_FISCAL = REPORTS + '/order-fiscal';

export type OrderReceiptUrlParams = {
  id?: string | {toString(): string};
  orderId?: string | number;
  invoice?: string | number;
};

export const orderReceiptUrl = (params: OrderReceiptUrlParams = {}) => {
  const search = new URLSearchParams();
  if (params.id != null && params.id !== '') {
    const raw = typeof params.id === 'string' ? params.id : params.id.toString();
    if (raw) {
      search.set('id', raw);
    }
  }
  if (params.orderId != null && params.orderId !== '') {
    search.set('order_id', String(params.orderId));
  }
  if (params.invoice != null && params.invoice !== '') {
    search.set('invoice', String(params.invoice));
  }
  const qs = search.toString();
  return qs ? `${REPORTS_ORDER_RECEIPT}?${qs}` : REPORTS_ORDER_RECEIPT;
};
export const REPORTS_EXPENSE = REPORTS + '/expense';
export const REPORTS_ACTIVITY = REPORTS + '/activity';
export const REPORTS_PRODUCT_HOURLY = REPORTS + '/product-hourly';
export const REPORTS_PRODUCT_LIST = REPORTS + '/product-list';
export const REPORTS_PRODUCT_MIX_SUMMARY = REPORTS + '/product-mix-summary';
export const REPORTS_SALES_ADVANCED = REPORTS + '/sales-advanced';
export const REPORTS_DELIVERY_DENSITY = REPORTS + '/delivery-density';
export const REPORTS_SALES_HOURLY_LABOUR = REPORTS + '/sales-hourly-labour';
export const REPORTS_SALES_HOURLY_LABOUR_WEEKLY = REPORTS + '/sales-hourly-labour-weekly';
export const REPORTS_SALES_SERVER = REPORTS + '/sales-server';
export const REPORTS_SALES_SUMMARY = REPORTS + '/sales-summary';
export const REPORTS_SALES_SUMMARY2 = REPORTS + '/sales-summary-2';
export const REPORTS_SALES_WEEKLY = REPORTS + '/sales-weekly';
export const REPORTS_TIPS = REPORTS + '/tips';
export const REPORTS_TABLES_SUMMARY = REPORTS + '/tables-summary';
export const REPORTS_VOIDS = REPORTS + '/voids';
export const REPORTS_CURRENT_INVENTORY = REPORTS + '/current-inventory';
export const REPORTS_DETAILED_INVENTORY = REPORTS + '/detailed-inventory';
export const REPORTS_PURCHASE = REPORTS + '/purchase';
export const REPORTS_PURCHASE_ORDER = REPORTS + '/purchase-order';
export const REPORTS_PURCHASE_RETURN = REPORTS + '/purchase-return';
export const REPORTS_ISSUE = REPORTS + '/issue';
export const REPORTS_ISSUE_RETURN = REPORTS + '/issue-return';
export const REPORTS_WASTE = REPORTS + '/waste';
export const REPORTS_CONSUMPTION = REPORTS + '/consumption';
export const REPORTS_SALE_VS_CONSUMPTION = REPORTS + '/sale-vs-consumption';
export const REPORTS_KITCHEN_RECONCILIATION = REPORTS + '/kitchen-reconciliation';
export const REPORTS_PRODUCTION = REPORTS + '/production';
export const REPORTS_BUFFET = REPORTS + '/buffet';
export const REPORTS_AI = REPORTS + '/ai';
export const REPORTS_FORECAST = REPORTS + '/forecast';
export const REPORTS_MENU_OPTIMIZATION = REPORTS + '/menu-optimization';
export const REPORTS_SENTIMENT = REPORTS + '/sentiment';
export const REPORTS_WASTE_INTELLIGENCE = REPORTS + '/waste-intelligence';
export const REPORTS_SCHEDULING_OPTIMIZATION = REPORTS + '/scheduling-optimization';
export const REPORTS_CASH_FLOW = REPORTS + '/cash-flow';
export const REPORTS_VENDOR_PERFORMANCE = REPORTS + '/vendor-performance';
export const REPORTS_TABLE_TURNOVER = REPORTS + '/table-turnover';
export const REPORTS_DYNAMIC_PRICING = REPORTS + '/dynamic-pricing';
export const REPORTS_FORECAST_ACCURACY = REPORTS + '/forecast-accuracy';
export const REPORTS_UPSELL_EFFECTIVENESS = REPORTS + '/upsell-effectiveness';
export const REPORTS_AI_COMMAND_CENTER = REPORTS + '/ai-command-center';
export const REPORTS_ANOMALY_ALERTS = REPORTS + '/anomaly-alerts';
export const REPORTS_CUSTOMER_CLV = REPORTS + '/customer-clv';
export const REPORTS_CHURN_PREDICTION = REPORTS + '/churn-prediction';
export const REPORTS_PROMO_EFFECTIVENESS = REPORTS + '/promo-effectiveness';
export const REPORTS_SERVER_PERFORMANCE = REPORTS + '/server-performance';
export const REPORTS_COMPETITOR_MONITORING = REPORTS + '/competitor-monitoring';
export const REPORTS_FOOD_COST_TRENDS = REPORTS + '/food-cost-trends';
export const REPORTS_RECIPE_OPTIMIZATION = REPORTS + '/recipe-optimization';
export const REPORTS_SEGMENTATION = REPORTS + '/segmentation';
export const REPORTS_LABOR_OPTIMIZATION = REPORTS + '/labor-optimization';
export const REPORTS_DELIVERY_ANALYTICS = REPORTS + '/delivery-analytics';
export const REPORTS_PEAK_HOUR = REPORTS + '/peak-hour';
export const REPORTS_TIP_ANALYTICS = REPORTS + '/tip-analytics';
export const REPORTS_REVPASH = REPORTS + '/revpash';
export const REPORTS_CUSTOMER_JOURNEY = REPORTS + '/customer-journey';
export const REPORTS_SEASONAL_TRENDS = REPORTS + '/seasonal-trends';
export const REPORTS_GUEST_PREFERENCES = REPORTS + '/guest-preferences';
export const REPORTS_SHRINKAGE = REPORTS + '/shrinkage-detection';
export const REPORTS_REVENUE_FORECAST = REPORTS + '/revenue-forecast';
export const REPORTS_NOSHOW_PREDICTION = REPORTS + '/no-show-prediction';
export const REPORTS_ORDER_FRAUD = REPORTS + '/order-fraud';
export const REPORTS_FOOD_SAFETY = REPORTS + '/food-safety';
export const REPORTS_ENERGY_OPTIMIZATION = REPORTS + '/energy-optimization';
export const REPORTS_STAFF_TURNOVER = REPORTS + '/staff-turnover';
export const REPORTS_YIELD_VARIANCE = REPORTS + '/yield-variance';
export const REPORTS_KITCHEN_BOTTLENECK = REPORTS + '/kitchen-bottleneck';
export const REPORTS_WIN_BACK = REPORTS + '/win-back';
export const REPORTS_CHARGEBACK_RISK = REPORTS + '/chargeback-risk';
export const REPORTS_PRICE_ELASTICITY = REPORTS + '/price-elasticity';
export const REPORTS_PROMO_ABUSE = REPORTS + '/promo-abuse';
export const REPORTS_MENU_PAIRING = REPORTS + '/menu-pairing';
export const REPORTS_WAIT_PREDICTION = REPORTS + '/wait-prediction';
export const REPORTS_PROMO_FORECAST = REPORTS + '/promo-forecast';
export const REPORTS_CLV_TRAJECTORY = REPORTS + '/clv-trajectory';
export const REPORTS_SPOILAGE_PREDICTION = REPORTS + '/spoilage-prediction';
export const REPORTS_VISIT_CADENCE = REPORTS + '/visit-cadence';
export const REPORTS_RECIPE_SUBSTITUTION = REPORTS + '/recipe-substitution';
export const REPORTS_TRAINING_NEED = REPORTS + '/training-need';
export const REPORTS_SEATING_OPTIMIZATION = REPORTS + '/seating-optimization';
export const REPORTS_SATISFACTION_PREDICTION = REPORTS + '/satisfaction-prediction';
export const REPORTS_ABANDONED_CART = REPORTS + '/abandoned-cart';
export const REPORTS_BRANCH_COMPARISON = REPORTS + '/branch-comparison';
export const REPORTS_COMPLIANCE_TRACKING = REPORTS + '/compliance-tracking';
export const REPORTS_GIFTCARD_FRAUD = REPORTS + '/giftcard-fraud';
export const REPORTS_REFUND_ABUSE = REPORTS + '/refund-abuse';
export const REPORTS_BUFFET_DEMAND = REPORTS + '/buffet-demand';
export const REPORTS_DELIVERY_ROUTE = REPORTS + '/delivery-route';
export const REPORTS_SERVER_LOAD_BALANCER = REPORTS + '/server-load-balancer';
export const REPORTS_DISH_PROFITABILITY = REPORTS + '/dish-profitability';
export const REPORTS_CASH_DRAWER_ANOMALY = REPORTS + '/cash-drawer-anomaly';
export const REPORTS_CASH_EARLY_WARNING = REPORTS + '/cash-early-warning';
export const REPORTS_COMPLAINT_PATTERN = REPORTS + '/complaint-pattern';
export const REPORTS_WEATHER_IMPACT = REPORTS + '/weather-impact';
export const REPORTS_PEAK_PRICING = REPORTS + '/peak-pricing';
export const REPORTS_TABLE_UTILIZATION = REPORTS + '/table-utilization';
export const REPORTS_OVERTIME_PREDICTION = REPORTS + '/overtime-prediction';
export const REPORTS_LOYALTY_ROI = REPORTS + '/loyalty-roi';
export const REPORTS_PROCUREMENT = REPORTS + '/procurement';
export const REPORTS_MENU_ROTATION = REPORTS + '/menu-rotation';
export const REPORTS_SERVER_COACH = REPORTS + '/server-coach';
export const REPORTS_ALLERGEN_RISK = REPORTS + '/allergen-risk';
export const REPORTS_OVERBOOKING = REPORTS + '/overbooking';
export const REPORTS_RESERVATION_CASCADE = REPORTS + '/reservation-cascade';
export const REPORTS_VIBE_OPTIMIZER = REPORTS + '/vibe-optimizer';
export const REPORTS_ENERGY_VAMPIRE = REPORTS + '/energy-vampire';
export const REPORTS_REVIEW_RESPONSE = REPORTS + '/review-response';
export const REPORTS_SOCIAL_CONTENT = REPORTS + '/social-content';
export const REPORTS_CATERING_OPTIMIZER = REPORTS + '/catering-optimizer';
export const REPORTS_EQUIPMENT_MAINTENANCE = REPORTS + '/equipment-maintenance';
export const REPORTS_MILESTONE_CAMPAIGN = REPORTS + '/milestone-campaign';
export const REPORTS_SCHEDULE_PREFERENCE = REPORTS + '/schedule-preference';
export const REPORTS_FLOOR_PLAN_OPTIMIZER = REPORTS + '/floor-plan-optimizer';
export const REPORTS_ONLINE_FRAUD_DETECTOR = REPORTS + '/online-fraud-detector';
export const REPORTS_PACKAGING_OPTIMIZER = REPORTS + '/packaging-optimizer';
export const REPORTS_REORDER_POINT_OPTIMIZER = REPORTS + '/reorder-point-optimizer';
export const REPORTS_PREP_SHEET_OPTIMIZER = REPORTS + '/prep-sheet-optimizer';
export const REPORTS_PAYMENT_FEE_OPTIMIZER = REPORTS + '/payment-fee-optimizer';
export const REPORTS_HEALTH_INSPECTION_READINESS = REPORTS + '/health-inspection-readiness';
export const REPORTS_SCHEDULE_CONFLICT_RESOLVER = REPORTS + '/schedule-conflict-resolver';
export const REPORTS_BREAK_EVEN_TRACKER = REPORTS + '/break-even-tracker';
export const REPORTS_ALCOHOL_COMPLIANCE_MONITOR = REPORTS + '/alcohol-compliance-monitor';
export const REPORTS_RECIPE_NUTRITION_GENERATOR = REPORTS + '/recipe-nutrition-generator';
export const REPORTS_ORDER_CUSTOMIZATION_ANALYZER = REPORTS + '/order-customization-analyzer';
export const REPORTS_TABLE_TURNOVER_PREDICTOR = REPORTS + '/table-turnover-predictor';
export const REPORTS_OPENING_CLOSING_AUTOMATOR = REPORTS + '/opening-closing-automator';
export const REPORTS_CARBON_FOOTPRINT_TRACKER = REPORTS + '/carbon-footprint-tracker';
export const REPORTS_AD_ROI_TRACKER = REPORTS + '/ad-roi-tracker';
export const REPORTS_COMPENSATION_OPTIMIZER = REPORTS + '/compensation-optimizer';
export const REPORTS_TAX_DEDUCTION_FINDER = REPORTS + '/tax-deduction-finder';
export const REPORTS_PHONE_ORDER_OPTIMIZER = REPORTS + '/phone-order-optimizer';
export const REPORTS_PREDICTIVE_ORDERING = REPORTS + '/predictive-ordering';
export const REPORTS_COMPETITOR_INTELLIGENCE = REPORTS + '/competitor-intelligence';
export const REPORTS_MULTI_LOCATION_BENCHMARK = REPORTS + '/multi-location-benchmark';
export const REPORTS_WASTE_TO_VALUE = REPORTS + '/waste-to-value';
export const REPORTS_SOCIAL_LISTENING = REPORTS + '/social-listening';
export const REPORTS_HIRING_PREDICTOR = REPORTS + '/hiring-predictor';

// Differentials 17-59 (batch addition)
export const REPORTS_RECIPE_SCALING = REPORTS + '/recipe-scaling';
export const REPORTS_WINE_PAIRING = REPORTS + '/wine-pairing';
export const REPORTS_STAFF_GAMIFICATION = REPORTS + '/staff-gamification';
export const REPORTS_KITCHEN_PREP_SCHEDULER = REPORTS + '/kitchen-prep-scheduler';
export const REPORTS_INVENTORY_TRANSFER = REPORTS + '/inventory-transfer';
export const REPORTS_SENTIMENT_TREND = REPORTS + '/sentiment-trend';
export const REPORTS_CLEANING_SCHEDULER = REPORTS + '/cleaning-scheduler';
export const REPORTS_DRIVER_COACH = REPORTS + '/driver-coach';
export const REPORTS_EXPIRY_TRACKER = REPORTS + '/expiry-tracker';
export const REPORTS_AD_TARGETING = REPORTS + '/ad-targeting';
export const REPORTS_LOCAL_SEO = REPORTS + '/local-seo';
export const REPORTS_PRICE_PSYCHOLOGY = REPORTS + '/price-psychology';
export const REPORTS_CASH_STRESS_TEST = REPORTS + '/cash-stress-test';
export const REPORTS_EVENT_MENU = REPORTS + '/event-menu';
export const REPORTS_RETENTION_PROGRAM = REPORTS + '/retention-program';
export const REPORTS_SUPPLIER_NEGOTIATION = REPORTS + '/supplier-negotiation';
export const REPORTS_MAINTENANCE_BUDGET = REPORTS + '/maintenance-budget';
export const REPORTS_FEEDBACK_LOOP = REPORTS + '/feedback-loop';
export const REPORTS_CROSS_SELL = REPORTS + '/cross-sell';
export const REPORTS_DISH_POPULARITY = REPORTS + '/dish-popularity';
export const REPORTS_WAITLIST_OPTIMIZER = REPORTS + '/waitlist-optimizer';

export const REPORTS_LABOR_DASHBOARD = REPORTS + '/labor-dashboard';
export const REPORTS_LABOR_DAILY_COST = REPORTS + '/labor-daily-cost';
export const REPORTS_LABOR_WEEKLY_COST = REPORTS + '/labor-weekly-cost';
export const REPORTS_LABOR_MONTHLY_COST = REPORTS + '/labor-monthly-cost';
export const REPORTS_LABOR_EMPLOYEE_COST = REPORTS + '/labor-employee-cost';
export const REPORTS_LABOR_DEPARTMENT_COST = REPORTS + '/labor-department-cost';
export const REPORTS_LABOR_COST_CENTER_COST = REPORTS + '/labor-cost-center-cost';
export const REPORTS_LABOR_OVERTIME = REPORTS + '/labor-overtime';
export const REPORTS_LABOR_ATTENDANCE = REPORTS + '/labor-attendance';
export const REPORTS_LABOR_LATE_ARRIVAL = REPORTS + '/labor-late-arrival';
export const REPORTS_LABOR_ABSENCE = REPORTS + '/labor-absence';
export const REPORTS_LABOR_LEAVE = REPORTS + '/labor-leave';
export const REPORTS_LABOR_HOLIDAY_COST = REPORTS + '/labor-holiday-cost';
export const REPORTS_LABOR_SCHEDULED_VS_ACTUAL = REPORTS + '/labor-scheduled-vs-actual';
export const REPORTS_LABOR_SCHEDULE_ROSTER = REPORTS + '/labor-schedule-roster';
export const REPORTS_LABOR_MANAGER_APPROVAL = REPORTS + '/labor-manager-approval';
export const REPORTS_LABOR_PAYROLL_SUMMARY = REPORTS + '/labor-payroll-summary';
export const REPORTS_LABOR_PAYROLL_DETAILS = REPORTS + '/labor-payroll-details';
export const REPORTS_LABOR_TREND = REPORTS + '/labor-trend';
export const REPORTS_LABOR_FORECAST = REPORTS + '/labor-forecast';export const REPORTS_VENDOR_INVOICE_AUDIT = REPORTS + '/vendor-invoice-audit';
export const REPORTS_BREAK_COMPLIANCE = REPORTS + '/break-compliance';
export const REPORTS_UTILITY_BILL_OPTIMIZER = REPORTS + '/utility-bill-optimizer';
export const REPORTS_ORDER_PACING = REPORTS + '/order-pacing';
export const REPORTS_SENTIMENT_HEATMAP = REPORTS + '/sentiment-heatmap';
export const REPORTS_DELIVERY_ZONE_OPTIMIZER = REPORTS + '/delivery-zone-optimizer';
export const REPORTS_PRICE_AB_TESTING = REPORTS + '/price-ab-testing';
export const REPORTS_MENU_ENGINEERING_MATRIX = REPORTS + '/menu-engineering-matrix';
export const REPORTS_PROMO_HALO_EFFECT = REPORTS + '/promo-halo-effect';
export const REPORTS_KITCHEN_DEMAND_SURGE = REPORTS + '/kitchen-demand-surge';
export const REPORTS_ORDER_MODIFICATION_PATTERN = REPORTS + '/order-modification-pattern';
export const REPORTS_CUSTOMER_LTV_MULTIPLIER = REPORTS + '/customer-ltv-multiplier';
export const REPORTS_TICKET_COMPLEXITY = REPORTS + '/ticket-complexity';
export const REPORTS_KITCHEN_STATION_EFFICIENCY = REPORTS + '/kitchen-station-efficiency';
export const REPORTS_PAIRING_AFFINITY = REPORTS + '/pairing-affinity';
export const REPORTS_WAIT_EXPERIENCE = REPORTS + '/wait-experience';
export const REPORTS_SERVER_TABLE_ASSIGNMENT = REPORTS + '/server-table-assignment';
export const REPORTS_SEASONAL_DEMAND_SHIFT = REPORTS + '/seasonal-demand-shift';
export const REPORTS_TABLE_TURNOVER_VELOCITY = REPORTS + '/table-turnover-velocity';
export const REPORTS_PROFITABILITY_DECAY = REPORTS + '/profitability-decay';
export const REPORTS_ORDER_FREQUENCY = REPORTS + '/order-frequency';
export const REPORTS_ORDER_PATTERN_ANOMALY = REPORTS + '/order-pattern-anomaly';
export const REPORTS_KITCHEN_SKILL_GAP = REPORTS + '/kitchen-skill-gap';
export const REPORTS_MENU_CANNIBALIZATION = REPORTS + '/menu-cannibalization';
export const REPORTS_JOURNEY_FRICTION = REPORTS + '/journey-friction';
export const REPORTS_SUBSTITUTION_IMPACT = REPORTS + '/substitution-impact';
export const REPORTS_PREFERENCE_DRIFT = REPORTS + '/preference-drift';
export const REPORTS_SHIFT_HANDOVER = REPORTS + '/shift-handover';
export const REPORTS_MENU_DESCRIPTION = REPORTS + '/menu-description';
export const REPORTS_CROSS_CHANNEL_ATTRIBUTION = REPORTS + '/cross-channel-attribution';
export const REPORTS_STAFF_ENERGY = REPORTS + '/staff-energy';
export const REPORTS_MENU_PHOTOGRAPHY = REPORTS + '/menu-photography';
export const REPORTS_TABLE_PREFERENCE = REPORTS + '/table-preference';
export const REPORTS_ELASTICITY_DRIFT = REPORTS + '/elasticity-drift';
export const REPORTS_OCCASION_PREDICTION = REPORTS + '/occasion-prediction';
export const REPORTS_MENU_ITEM_RETIREMENT = REPORTS + '/menu-item-retirement';
export const REPORTS_STAFF_PERFORMANCE_PREDICTION = REPORTS + '/staff-performance-prediction';
export const REPORTS_ATMOSPHERE_REVENUE = REPORTS + '/atmosphere-revenue';
export const REPORTS_PRE_SHIFT_BRIEFING = REPORTS + '/pre-shift-briefing';
export const REPORTS_RECIPE_COST_VOLATILITY = REPORTS + '/recipe-cost-volatility';
export const REPORTS_PLATE_WASTE_PREDICTOR = REPORTS + '/plate-waste-predictor';
export const REPORTS_LOYALTY_TIER_MIGRATION = REPORTS + '/loyalty-tier-migration';
export const REPORTS_FIRST_VISIT_CONVERSION = REPORTS + '/first-visit-conversion';
export const REPORTS_DELIVERY_QUALITY_DECAY = REPORTS + '/delivery-quality-decay';
export const REPORTS_BAR_POUR_VARIANCE = REPORTS + '/bar-pour-variance';
export const REPORTS_RESTROOM_CLEANLINESS = REPORTS + '/restroom-cleanliness';
export const REPORTS_WIFI_EXPERIENCE = REPORTS + '/wifi-experience';
export const REPORTS_PARKING_LOT_OPTIMIZER = REPORTS + '/parking-lot-optimizer';
export const REPORTS_NOISE_ACOUSTIC_COMFORT = REPORTS + '/noise-acoustic-comfort';
export const REPORTS_LIGHTING_MOOD_OPTIMIZER = REPORTS + '/lighting-mood-optimizer';
export const REPORTS_TEMPERATURE_HVAC_COMFORT = REPORTS + '/temperature-hvac-comfort';
export const REPORTS_SCENT_MARKETING_OPTIMIZER = REPORTS + '/scent-marketing-optimizer';
export const REPORTS_ENTRANCE_ARRIVAL_OPTIMIZER = REPORTS + '/entrance-arrival-optimizer';
export const REPORTS_MENU_LAYOUT_PLACEMENT = REPORTS + '/menu-layout-placement';
export const REPORTS_STAFF_APPEARANCE_UNIFORM = REPORTS + '/staff-appearance-uniform';
export const REPORTS_MUSIC_PLAYLIST_ROTATION = REPORTS + '/music-playlist-rotation';
export const REPORTS_TABLE_SETTING_TABLEWARE = REPORTS + '/table-setting-tableware';
export const REPORTS_SEATING_COMFORT_FURNITURE = REPORTS + '/seating-comfort-furniture';
export const REPORTS_WALL_DECOR_ARTWORK = REPORTS + '/wall-decor-artwork';
export const REPORTS_BIOPHILIC_DESIGN_PLANT = REPORTS + '/biophilic-design-plant';
export const REPORTS_DIGITAL_MENU_QR = REPORTS + '/digital-menu-qr';
export const REPORTS_OUTDOOR_PATIO_SEASONAL = REPORTS + '/outdoor-patio-seasonal';
export const REPORTS_AIR_QUALITY_VENTILATION = REPORTS + '/air-quality-ventilation';
export const REPORTS_CURB_APPEAL_FACADE = REPORTS + '/curb-appeal-facade';
export const REPORTS_FLOOR_CEILING_SURFACE = REPORTS + '/floor-ceiling-surface';
export const REPORTS_INTERIOR_SIGNAGE_WAYFINDING = REPORTS + '/interior-signage-wayfinding';
export const REPORTS_COLOR_SCHEME_PALETTE = REPORTS + '/color-scheme-palette';
export const REPORTS_WINDOW_NATURAL_LIGHT = REPORTS + '/window-natural-light';
export const REPORTS_MENU_TYPOGRAPHY_MATERIAL = REPORTS + '/menu-typography-material';
export const REPORTS_MIRROR_REFLECTIVE_SURFACE = REPORTS + '/mirror-reflective-surface';
export const REPORTS_ROOM_PARTITION_DIVIDER = REPORTS + '/room-partition-divider';
export const REPORTS_RESTROOM_DESIGN_FIXTURE = REPORTS + '/restroom-design-fixture';
export const REPORTS_FIREPLACE_FIRE_FEATURE = REPORTS + '/fireplace-fire-feature';
export const REPORTS_CEILING_DESIGN_DECOR = REPORTS + '/ceiling-design-decor';
export const REPORTS_GREEN_CERTIFICATION_ECO = REPORTS + '/green-certification-eco';
export const REPORTS_SOUND_SYSTEM_SPEAKER = REPORTS + '/sound-system-speaker';
export const REPORTS_PRIVATE_EVENT_SPACE = REPORTS + '/private-event-space';
export const REPORTS_FOOD_DISPLAY_PASTRY_CASE = REPORTS + '/food-display-pastry-case';
export const REPORTS_BRANDED_MERCH_RETAIL = REPORTS + '/branded-merchandise-retail';
export const REPORTS_COMMUNITY_PARTNERSHIP_ENGAGEMENT = REPORTS + '/community-partnership-engagement';
export const REPORTS_SELF_SERVICE_KIOSK_TERMINAL = REPORTS + '/self-service-kiosk-terminal';
export const REPORTS_MOBILE_APP_ORDERING = REPORTS + '/mobile-app-ordering';
export const REPORTS_PHONE_CHARGING_POWER = REPORTS + '/phone-charging-power';
export const REPORTS_TABLETOP_ENTERTAINMENT_ACTIVITY = REPORTS + '/tabletop-entertainment-activity';
export const REPORTS_OUTDOOR_LANDSCAPE_LIGHTING = REPORTS + '/outdoor-landscape-lighting';
export const REPORTS_WATER_STATION_BEVERAGE_BAR = REPORTS + '/water-station-beverage-bar';
export const REPORTS_NUTRITIONAL_TRANSPARENCY = REPORTS + '/nutritional-transparency';
export const REPORTS_CULINARY_EXPERIENCE_COOKING_CLASS = REPORTS + '/culinary-experience-cooking-class';
export const REPORTS_LIVE_MUSIC_PERFORMANCE = REPORTS + '/live-music-performance';
export const REPORTS_WINDOW_TREATMENT_CURTAIN = REPORTS + '/window-treatment-curtain';
export const REPORTS_ROTATING_ART_GALLERY = REPORTS + '/rotating-art-gallery';
export const REPORTS_FAMILY_INFANT_AMENITY = REPORTS + '/family-infant-amenity';
export const REPORTS_COAT_CHECK_CLOAKROOM = REPORTS + '/coat-check-cloakroom';
export const REPORTS_TAKEOUT_PACKAGING_CONTAINER = REPORTS + '/takeout-packaging-container';
export const REPORTS_DRIVE_THRU_PICKUP_WINDOW = REPORTS + '/drive-thru-pickup-window';
export const REPORTS_SENSORY_FRIENDLY_SPACE = REPORTS + '/sensory-friendly-space';
export const REPORTS_PET_FRIENDLY_SERVICE_ANIMAL = REPORTS + '/pet-friendly-service-animal';
export const REPORTS_ACCESSIBILITY_MENU_ADA = REPORTS + '/accessibility-menu-ada';
export const REPORTS_SEASONAL_HOLIDAY_DECOR = REPORTS + '/seasonal-holiday-decor';
export const REPORTS_CELEBRATION_SERVICE_OPTIMIZER = REPORTS + '/celebration-service-optimizer';
export const REPORTS_INFLUENCER_OUTREACH_OPTIMIZER = REPORTS + '/influencer-outreach-optimizer';
export const REPORTS_STAFF_MENTAL_HEALTH_WELLNESS = REPORTS + '/staff-mental-health-wellness';
export const REPORTS_GHOST_KITCHEN_VIRTUAL_BRAND = REPORTS + '/ghost-kitchen-virtual-brand';
export const REPORTS_SUBSCRIPTION_MEMBERSHIP_PROGRAM = REPORTS + '/subscription-membership-program';
export const REPORTS_VOICE_ORDERING_CONVERSATIONAL_AI = REPORTS + '/voice-ordering-conversational-ai';
export const REPORTS_CRISIS_COMMUNICATION_PR_REPUTATION = REPORTS + '/crisis-communication-pr-reputation';
