'use strict';

const express = require('express');
const {
  createIntent,
  verifyPayment,
} = require('../controllers/payments.controller');

const router = express.Router();

router.get('/checkout/:gateway/:token', (req, res) => {
  const { gateway, token } = req.params;
  res.status(200).send(
    `<!doctype html><html><head><meta charset="utf-8"><title>Payment Checkout</title></head><body style="font-family:system-ui,sans-serif;padding:24px;"><h2>Payment Checkout Stub</h2><p>Gateway: <strong>${gateway}</strong></p><p>Token: <code>${token}</code></p><p>This URL is generated by the payment service and can be replaced with real gateway checkout/redirection logic.</p></body></html>`
  );
});

router.post('/create-intent', createIntent);
router.post('/verify', verifyPayment);

module.exports = router;
