export enum Tables {
  categories = 'category',
  closings = 'closing',
  customers = 'customer',
  discounts = 'discount',
  floors = 'floor',
  tables = 'floor_table',
  kitchens = 'kitchen',
  dishes = 'menu_item',
  dishes_recipes = 'menu_item_recipe',
  modifier_groups = 'modifier_group',
  modifiers = 'modifier',
  dish_modifier_groups = 'menu_item_modifier_group',

  orders = 'order',
  order_extras = 'order_extras',
  order_items = 'order_item',
  order_items_kitchen = 'order_item_kitchen',
  order_meta = 'order_meta',
  order_payment = 'order_payment',
  order_merge = 'order_merge',
  order_voids = 'order_void',
  order_refunds = 'order_refund',

  order_types = 'order_type',
  payment_types = 'payment_type',
  printers = 'printer',
  taxes = 'tax',
  users = 'user',
  time_entries = 'time_entry',

  inventory_items = 'inventory_item',
  inventory_suppliers = 'inventory_supplier',
  inventory_categories = 'inventory_category',
  inventory_stores = 'inventory_store',
  inventory_purchase_orders = 'inventory_purchase_order',
  inventory_purchase_order_items = 'inventory_purchase_order_item',
  inventory_purchases = 'inventory_purchase',
  inventory_purchase_items = 'inventory_purchase_item',
  inventory_purchase_returns = 'inventory_purchase_return',
  inventory_purchase_return_items = 'inventory_purchase_return_item',
  inventory_issues = 'inventory_issue',
  inventory_issue_items = 'inventory_issue_item',
  inventory_issue_returns = 'inventory_issue_return',
  inventory_issue_return_items = 'inventory_issue_return_item',
  inventory_item_groups = 'inventory_item_group',
  inventory_item_group_items = 'inventory_item_group_item',
  inventory_wastes = 'inventory_item_waste',
  inventory_waste_items = 'inventory_item_waste_item',

  settings = 'setting'
}
