export enum Tables {
  categories = 'category',
  customers = 'customer',
  discounts = 'discount',
  floors = 'floor',
  tables = 'floor_table',
  kitchens = 'kitchen',
  dishes = 'menu_item',
  modifier_groups = 'modifier_group',
  modifiers = 'modifier',
  dish_modifier_groups = 'menu_item_modifier_group',
  orders = 'order',
  order_extras = 'order_extras',
  order_items = 'order_item',
  order_items_kitchen = 'order_item_kitchen',
  order_meta = 'order_meta',
  order_payment = 'order_payment',
  order_types = 'order_type',
  payment_types = 'payment_type',
  printers = 'printer',
  taxes = 'tax',
  users = 'user',
}
